services:
  dev-ubuntu:
    image: ubuntu:latest
    container_name: dev-ubuntu
    tty: true
    stdin_open: true
    ports:
      - "0.0.0.0:1455:1455"
    volumes:
      - dev-ubuntu_data:/

volumes:
  dev-ubuntu_data:
